version: '3.1'

services:
  api:
    build: .
    ports:
      - 3000:80
      - 3001:443
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CUSTOMCONNSTR_CommerceConnection: Server=db;Database=commerce_db;Username=postgres;Password=Outdoors123
      ASPNETCORE_URLS: http://*:80
    volumes:
      - $HOME/.aspnet/https:/https:ro
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "dotnet", "CommerceApi.dll"]
  db:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: Outdoors123
    ports:
      - 5432:5432
    volumes: 
      - postgres_db:/var/lib/postgresql/data

volumes: 
  postgres_db:
