// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShippingEcommerce.Data;

namespace ShippingEcommerce.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210511024223_HolidaysSeedDAta")]
    partial class HolidaysSeedDAta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("postgis")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ShippingEcommerce.Data.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new NodaTime.LocalDate(2021, 1, 1),
                            Name = "New Year's Day"
                        },
                        new
                        {
                            Id = 2,
                            Date = new NodaTime.LocalDate(2021, 1, 20),
                            Name = "Birthday of Martin Luther King, Jr."
                        },
                        new
                        {
                            Id = 3,
                            Date = new NodaTime.LocalDate(2021, 2, 17),
                            Name = "Presidents' Day"
                        },
                        new
                        {
                            Id = 4,
                            Date = new NodaTime.LocalDate(2021, 5, 25),
                            Name = "Memorial Day"
                        },
                        new
                        {
                            Id = 5,
                            Date = new NodaTime.LocalDate(2021, 7, 4),
                            Name = "Independence Day"
                        },
                        new
                        {
                            Id = 6,
                            Date = new NodaTime.LocalDate(2021, 9, 7),
                            Name = "Labor Day"
                        },
                        new
                        {
                            Id = 7,
                            Date = new NodaTime.LocalDate(2021, 10, 12),
                            Name = "Columbus Day"
                        },
                        new
                        {
                            Id = 8,
                            Date = new NodaTime.LocalDate(2021, 11, 11),
                            Name = "Veterans Day"
                        },
                        new
                        {
                            Id = 9,
                            Date = new NodaTime.LocalDate(2021, 11, 26),
                            Name = "Thanksgiving Day"
                        },
                        new
                        {
                            Id = 10,
                            Date = new NodaTime.LocalDate(2021, 12, 25),
                            Name = "Christmas Day"
                        });
                });

            modelBuilder.Entity("ShippingEcommerce.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBusinessDaysToShip")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<bool>("ShipOnWeekends")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            InventoryQuantity = 43,
                            MaxBusinessDaysToShip = 13,
                            ProductName = "fugiat exercitation adipisicing",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryQuantity = 70,
                            MaxBusinessDaysToShip = 18,
                            ProductName = "mollit cupidatat Lorem",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryQuantity = 33,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "non quis sint",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryQuantity = 52,
                            MaxBusinessDaysToShip = 18,
                            ProductName = "voluptate cupidatat non",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryQuantity = 39,
                            MaxBusinessDaysToShip = 19,
                            ProductName = "anim amet occaecat",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 6,
                            InventoryQuantity = 47,
                            MaxBusinessDaysToShip = 20,
                            ProductName = "cillum deserunt elit",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 7,
                            InventoryQuantity = 71,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "adipisicing reprehenderit et",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 8,
                            InventoryQuantity = 80,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "ex mollit laboris",
                            ShipOnWeekends = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
