// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShippingEcommerce.Data;

namespace ShippingEcommerce.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210509000449_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("postgis")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ShippingEcommerce.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBusinessDaysToShip")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<bool>("ShipOnWeekends")
                        .HasColumnType("boolean");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            InventoryQuantity = 43,
                            MaxBusinessDaysToShip = 13,
                            ProductName = "fugiat exercitation adipisicing",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 2,
                            InventoryQuantity = 70,
                            MaxBusinessDaysToShip = 18,
                            ProductName = "mollit cupidatat Lorem",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 3,
                            InventoryQuantity = 33,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "non quis sint",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 4,
                            InventoryQuantity = 52,
                            MaxBusinessDaysToShip = 18,
                            ProductName = "voluptate cupidatat non",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 5,
                            InventoryQuantity = 39,
                            MaxBusinessDaysToShip = 19,
                            ProductName = "anim amet occaecat",
                            ShipOnWeekends = true
                        },
                        new
                        {
                            ProductId = 6,
                            InventoryQuantity = 47,
                            MaxBusinessDaysToShip = 20,
                            ProductName = "cillum deserunt elit",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 7,
                            InventoryQuantity = 71,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "adipisicing reprehenderit et",
                            ShipOnWeekends = false
                        },
                        new
                        {
                            ProductId = 8,
                            InventoryQuantity = 80,
                            MaxBusinessDaysToShip = 15,
                            ProductName = "ex mollit laboris",
                            ShipOnWeekends = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
